#based on a nice history lesson from: https://www.codingninjas.com/blog/2020/12/29/working-with-multiple-java-versions-on-linux/
---
- name: Install sdkman, java, maven
  hosts: localhost
  connection: local
  tasks:
  - name: "unzip & zip install"
    shell: >
     sudo dnf install -y unzip zip
  - name: "sdkman install"
    shell: >
     curl -s "https://get.sdkman.io" | bash
     creates=/home/{{ ansible_user_id }}/.sdkman/bin/sdkman-init.sh
  - name: "java 11 latest install"
    shell: >
     bash -lc "source /home/{{ ansible_user_id }}/.sdkman/src/sdkman-main.sh && sdk install java `sdk list java|grep tem|grep 11|head -n 1|awk '{print $NF}'`"
  - name: "java 17 latest install"
    shell: >
     bash -lc "source /home/{{ ansible_user_id }}/.sdkman/src/sdkman-main.sh && sdk install java `sdk list java|grep tem|grep 17|head -n 1|awk '{print $NF}'`"
  - name: "java graalvm latest install"
    shell: >
     bash -lc "source /home/{{ ansible_user_id }}/.sdkman/src/sdkman-main.sh && sdk install java `sdk list java|grep GraalVM|awk '{print $NF}'`"
  - name: "gradle install"
    shell: >
     bash -lc "source /home/{{ ansible_user_id }}/.sdkman/src/sdkman-main.sh && sdk install gradle"
  - name: "groovy install"
    shell: >
     bash -lc "source /home/{{ ansible_user_id }}/.sdkman/src/sdkman-main.sh && sdk install groovy"
  - name: "hadoop install"
    shell: >
     bash -lc "source /home/{{ ansible_user_id }}/.sdkman/src/sdkman-main.sh && sdk install hadoop"
  - name: "kotlin install"
    shell: >
     bash -lc "source /home/{{ ansible_user_id }}/.sdkman/src/sdkman-main.sh && sdk install kotlin"
  - name: "maven install"
    shell: >
     bash -lc "source /home/{{ ansible_user_id }}/.sdkman/src/sdkman-main.sh && sdk install maven"
  - name: "micronaut install"
    shell: >
     bash -lc "source /home/{{ ansible_user_id }}/.sdkman/src/sdkman-main.sh && sdk install micronaut"
  - name: "quarkus install"
    shell: >
     bash -lc "source /home/{{ ansible_user_id }}/.sdkman/src/sdkman-main.sh && sdk install quarkus"
     echo '# 02 Quarkus' >> ~/.bash_profile
     echo 'source <(quarkus completion)' >> ~/.bash_profile
     echo 'alias q=quarkus' >> ~/.bash_profile
     echo 'complete -F _complete_quarkus q' >> ~/.bash_profile
     echo '' >> ~/.bash_profile
  - name: "spark install"
    shell: >
     bash -lc "source /home/{{ ansible_user_id }}/.sdkman/src/sdkman-main.sh && sdk install spark"
