#based on sample code from: https://devapo.io/blog/technology/how-to-set-up-prometheus-on-kubernetes-with-helm-charts/
---
- name: Install prometheus and grafana
  hosts: localhost
  connection: local
  tasks:
  - name: "add prometheus-community helm repo, update and install"
    shell: >
     kubectl create namespace monitoring
     helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
     helm repo update
     helm install -n monitoring prometheus prometheus-community/prometheus
  - name: "add grafana helm repo, update and install"
    shell: >
     helm repo add bitnami https://charts.bitnami.com/bitnami
     helm repo update
     helm install -n monitoring grafana bitnami/grafana
     echo 'see https://blog.marcnuri.com/prometheus-grafana-setup-minikube:'
     echo 'login on Grafana with "admin" user and password:'
     echo `kubectl get secret grafana-admin --namespace monitoring -o jsonpath="{.data.GF_SECURITY_ADMIN_PASSWORD}" | base64 -d`
     echo 'add prometheus datasource on http://prometheus-server:80'
     echo 'Kubernetes Dashboard bootstrap: head to Create (+) > Import section to Import via grafana.com and we set 6417 into the id field and click Load. Choose prometheus datasource'
